# Docker Compose is used for spinning up the local-da docker container along with the GM container.

version: "3.8"
services:
  artroll:
    container_name: artroll
    # The build config can be used for debugging and testing changes to the Dockerfile
    build: .

    ports:
      - "8545:8545"  # forward port to your host machine

    # Always pull the latest image
    pull_policy: always

    # The command config is used for launching the GM rollup once the Docker container is running
    command: rollkit start --rollkit.aggregator --rollkit.da_address http://local-da:7980
    
    depends_on:
      - local-da

  local-da:
    image: ghcr.io/rollkit/local-da:v0.2.1
    container_name: local-da
    ports:
      - "7980:7980"
